name: Merge and deploy

on:
  push:
    branches: [ "master"]
  pull_request: 
    branches: [ "master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 18.x ]
        
    steps:
      - name: Build
        run: | 
          npm install
          
      - name: Run
        run: |
          npm run dev
          
      - name: Test
        run: |
          npm run test
    
      
      
