name: Merge and deploy

env:
    VITE_SUPABASE_KEY: ${{ vars.VITE_SUPABASE_KEY }}

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install packages
              run: |
                  npm install

            - name: build code
              run: |
                  npm run build
    
    status_build:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Check build staus
              if: ${{ needs.build.result == 'failure' }}
              run: echo "Build failed"

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                    node-version: 18

            - name: Install packages
              run: |
                    npm install

            - name: Test
              run: |
                npm run test

    status_check_on_failure:
        needs: [build, test]
        runs-on: ubuntu-latest

        steps:
            - name: Check build staus
              if: ${{ needs.build.result == 'failure' }}
              run: echo "Build failed"

            - name: Check build status
              if: ${{ needs.test.result == 'failure' }}
              run: echo "Tests failed!"
