name: Merge and deploy

on:
  push:
    branches: [ "master"]
  pull_request: 
    branches: [ "master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: | 
          npm install

      - name: Show env
        run: | 
          echo "My environment variable: $VITE_SUPABASE_KEY"
          
      - name: Test
        run: |
          npm run test
      